### ISSUE TITLE
Scratch should not save files without giving them file extensions

### ISSUE THREAD

**Issue by angjinhang** [elementary/scratch#233] opened 2017-10-14 05:03 UTC
Example: https://www.dropbox.com/s/qx30f5896194kza/Screencast%20from%202017-10-14%2012.30.22.webm?dl=0

Text description if no one watches vids: Open an empty file, save as, choose save as 'Text file', don't supply file extension in file name text box, save. It saves without giving any file extensions even though it should be saved as 'Text file'. 

It isn't a big issue if the entire world is using elementary OS (since files without extensions are opened with Scratch anyway), but then when users save these files on a pendrive and bring them around, they might think they got corrupted or something :thinking: 

It is said that it is impossible to fix due to limitations of Vala and GTK3, hope it's not true and this can get fixed :)

**Comment by danrabbit** [comment] 2017-10-14 07:24
File extensions are not required on Unix systems. This is not a bug. Closing as “won’t fix”

**Closed by danrabbit** 2017-10-14 07:24 UTC

**Comment by jeremypw** [comment] 2017-10-14 10:42
If you know it might be shared to non Unix systems then an extension can be added manually.
